### ISSUE TITLE
executing sample command from README doesn't work

### ISSUE THREAD

**Issue by agroschner** [mriedmann/periscope#1]
to get periscope.py running I had to add the following changes:

```
diff --git a/Dockerfile b/Dockerfile
index 5bb473b..adacea1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,6 +4,6 @@ WORKDIR /usr/src/app
 COPY requirements.txt ./
 RUN pip install --no-cache-dir -r requirements.txt
-COPY periscope.py ./
+COPY periscope.py checks.py ./
-ENTRYPOINT [ "python", "/usr/src/app/periscope.py" ]
\ No newline at end of file
+ENTRYPOINT [ "python", "/usr/src/app/periscope.py" ]
diff --git a/periscope.py b/periscope.py
index bfafefa..666f9ea 100755
--- a/periscope.py
+++ b/periscope.py
@@ -4,6 +4,10 @@ import argparse
 from termcolor import colored
 import yaml
 import concurrent.futures
+import importlib.util
+spec = importlib.util.spec_from_file_location("checks", "checks.py")
+foo = importlib.util.module_from_spec(spec)
+spec.loader.exec_module(foo)
 from checks import CheckResult, checks, Ok, Warn, Err
@@ -101,4 +105,4 @@ if __name__ == '__main__':
     if any(isinstance(x, Err) for x in results):
         exit(1)
     else:
-        exit(0)
\ No newline at end of file
+        exit(0)
diff --git a/requirements.txt b/requirements.txt
index 0a2e487..4cfe122 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,5 @@
 termcolor
 icmplib
 netaddr
-urllib3
\ No newline at end of file
+urllib3
+pyyaml
```

After building the container and running the sample command inside, the following error occured:
```
sudo docker run -it --entrypoint=/bin/sh --rm periscope
/usr/src/app # python periscope.py \
>   --http https://httpstat.us/200 \
>   --tcp  8.8.8.8:53 \
>   --ping 8.8.8.8 \
>   --dns  'dns.google=8.8.8.8,8.8.4.4'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/icmplib/sockets.py", line 88, in __init__
    self._sock = self._create_socket(
  File "/usr/local/lib/python3.9/site-packages/icmplib/sockets.py", line 452, in _create_socket
    return socket.socket(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/periscope.py", line 104, in <module>
    print_results(results)
  File "/usr/src/app/periscope.py", line 59, in print_results
    for result in results:
  File "/usr/src/app/periscope.py", line 71, in run
    yield future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/checks.py", line 38, in ping
    host = icmplib.ping(x, privileged=False,count=ping_count)
  File "/usr/local/lib/python3.9/site-packages/icmplib/ping.py", line 131, in ping
    sock = ICMPv4Socket(
  File "/usr/local/lib/python3.9/site-packages/icmplib/sockets.py", line 97, in __init__
    raise SocketPermissionError
icmplib.exceptions.SocketPermissionError: Root privileges are required to create the socket
```
even though the container itself is running as root as well as the user starting the command

Distro: Linux Mint 19 Tara
docker version:
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by mriedmann** [comment]
thx for the report. Should be fixed in latest version.
